# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: '*/1 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const options = github.issues.listForRepo.endpoint.merge({
              owner: 'af12066',
              repo: 'github-actions',
              state: 'open'
            });
            const issues = await github.paginate(options)
            const currentDatetime = new Date();

            for (const issue of issues) {
              const lastUpdateDatetime = new Date(issue.updated_at);
              const elapsedDay = Math.floor((currentDatetime - lastUpdateDatetime) / 1000 / 60 / 60 / 24);
              const isIssue = issue.pull_request === undefined;
              if (elapsedDay === 0 && isIssue) {
                github.issues.createComment({
                  owner: 'af12066',
                  repo: 'github-actions',
                  issue_number: issue.number,
                  body: 'post from github actions'
                });
              }
            }
